Name                                                Stmts   Miss  Cover
-----------------------------------------------------------------------
application/__init__.py                                 0      0   100%
application/local_settings.py                           1      0   100%
application/scriptDB.py                                 6      6     0%
application/settings.py                                24      2    92%
application/urls.py                                     3      0   100%
application/wsgi.py                                     4      4     0%
chats/__init__.py                                       0      0   100%
chats/admin.py                                          9      0   100%
chats/apps.py                                           3      3     0%
chats/chats_factory.py                                  5      5     0%
chats/forms.py                                         10      0   100%
chats/migrations/0001_initial.py                        6      0   100%
chats/migrations/0002_auto_20200307_2258.py             7      0   100%
chats/migrations/0003_auto_20200331_2257.py             4      0   100%
chats/migrations/0004_remove_chat_last_message.py       4      0   100%
chats/migrations/0005_auto_20200331_2301.py             5      0   100%
chats/migrations/__init__.py                            0      0   100%
chats/models.py                                        33      0   100%
chats/tests.py                                         46      0   100%
chats/tests_selenium.py                                14      8    43%
chats/urls.py                                           3      0   100%
chats/user_factory.py                                   6      0   100%
chats/views.py                                         76     41    46%
manage.py                                              12      2    83%
user/__init__.py                                        0      0   100%
user/admin.py                                           1      0   100%
user/apps.py                                            3      3     0%
user/forms.py                                           6      0   100%
user/migrations/0001_initial.py                         8      0   100%
user/migrations/__init__.py                             0      0   100%
user/models.py                                          7      0   100%
user/tests.py                                           1      1     0%
user/urls.py                                            3      0   100%
user/views.py                                           8      4    50%
-----------------------------------------------------------------------
TOTAL                                                 318     79    75%

