# Generated by Django 2.2.5 on 2020-03-31 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20200307_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='last_messege',
            new_name='last_message',
        ),
    ]
