# Generated by Django 2.2.5 on 2020-03-31 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_auto_20200331_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='last_message',
        ),
    ]
