# Generated by Django 2.2.5 on 2020-03-31 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_remove_chat_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_messege_id', to='chats.Message'),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.Message'),
        ),
    ]
